# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\tlseh\Desktop\temp\lectureCapture.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(560, 455)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(290, 455))
        MainWindow.setMaximumSize(QtCore.QSize(560, 455))
        MainWindow.setBaseSize(QtCore.QSize(560, 455))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser_output = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_output.setGeometry(QtCore.QRect(10, 190, 271, 192))
        self.textBrowser_output.setOpenExternalLinks(True)
        self.textBrowser_output.setObjectName("textBrowser_output")
        self.pdfCap_Button = QtWidgets.QPushButton(self.centralwidget)
        self.pdfCap_Button.setGeometry(QtCore.QRect(90, 140, 51, 41))
        self.pdfCap_Button.setAutoFillBackground(False)
        self.pdfCap_Button.setObjectName("pdfCap_Button")
        self.l_dir = QtWidgets.QLabel(self.centralwidget)
        self.l_dir.setGeometry(QtCore.QRect(10, 40, 91, 21))
        self.l_dir.setAlignment(QtCore.Qt.AlignCenter)
        self.l_dir.setObjectName("l_dir")
        self.lineEdit_lctr = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_lctr.setGeometry(QtCore.QRect(140, 10, 71, 20))
        self.lineEdit_lctr.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_lctr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_lctr.setObjectName("lineEdit_lctr")
        self.l_lctr = QtWidgets.QLabel(self.centralwidget)
        self.l_lctr.setGeometry(QtCore.QRect(10, 10, 91, 20))
        self.l_lctr.setAlignment(QtCore.Qt.AlignCenter)
        self.l_lctr.setObjectName("l_lctr")
        self.cancle_Button = QtWidgets.QPushButton(self.centralwidget)
        self.cancle_Button.setGeometry(QtCore.QRect(160, 140, 101, 41))
        self.cancle_Button.setObjectName("cancle_Button")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 120, 271, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.l_dir_show = QtWidgets.QLabel(self.centralwidget)
        self.l_dir_show.setGeometry(QtCore.QRect(110, 40, 121, 21))
        self.l_dir_show.setFrameShape(QtWidgets.QFrame.Box)
        self.l_dir_show.setText("")
        self.l_dir_show.setAlignment(QtCore.Qt.AlignCenter)
        self.l_dir_show.setObjectName("l_dir_show")
        self.clear_Button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_Button.setGeometry(QtCore.QRect(180, 390, 91, 21))
        self.clear_Button.setObjectName("clear_Button")
        self.path_Button = QtWidgets.QPushButton(self.centralwidget)
        self.path_Button.setGeometry(QtCore.QRect(240, 40, 41, 21))
        self.path_Button.setObjectName("path_Button")
        self.l_ePoint_show = QtWidgets.QLabel(self.centralwidget)
        self.l_ePoint_show.setGeometry(QtCore.QRect(110, 100, 121, 20))
        self.l_ePoint_show.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l_ePoint_show.setText("")
        self.l_ePoint_show.setAlignment(QtCore.Qt.AlignCenter)
        self.l_ePoint_show.setObjectName("l_ePoint_show")
        self.l_sPoint = QtWidgets.QLabel(self.centralwidget)
        self.l_sPoint.setGeometry(QtCore.QRect(10, 70, 91, 20))
        self.l_sPoint.setAlignment(QtCore.Qt.AlignCenter)
        self.l_sPoint.setObjectName("l_sPoint")
        self.l_sPoint_show = QtWidgets.QLabel(self.centralwidget)
        self.l_sPoint_show.setGeometry(QtCore.QRect(110, 70, 121, 20))
        self.l_sPoint_show.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.l_sPoint_show.setText("")
        self.l_sPoint_show.setAlignment(QtCore.Qt.AlignCenter)
        self.l_sPoint_show.setObjectName("l_sPoint_show")
        self.l_ePoint = QtWidgets.QLabel(self.centralwidget)
        self.l_ePoint.setGeometry(QtCore.QRect(10, 100, 91, 20))
        self.l_ePoint.setAlignment(QtCore.Qt.AlignCenter)
        self.l_ePoint.setObjectName("l_ePoint")
        self.position_Button = QtWidgets.QPushButton(self.centralwidget)
        self.position_Button.setGeometry(QtCore.QRect(240, 70, 41, 51))
        self.position_Button.setObjectName("position_Button")
        self.checkBox_lastChk = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_lastChk.setGeometry(QtCore.QRect(320, 30, 221, 41))
        self.checkBox_lastChk.setChecked(False)
        self.checkBox_lastChk.setObjectName("checkBox_lastChk")
        self.checkBox_endClr = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_endClr.setGeometry(QtCore.QRect(320, 110, 221, 31))
        self.checkBox_endClr.setChecked(True)
        self.checkBox_endClr.setObjectName("checkBox_endClr")
        self.setOpen_Button = QtWidgets.QPushButton(self.centralwidget)
        self.setOpen_Button.setGeometry(QtCore.QRect(230, 0, 51, 31))
        self.setOpen_Button.setObjectName("setOpen_Button")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(290, 10, 31, 401))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(3)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 0, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.folderOpen_Button = QtWidgets.QPushButton(self.centralwidget)
        self.folderOpen_Button.setGeometry(QtCore.QRect(20, 390, 91, 23))
        self.folderOpen_Button.setObjectName("folderOpen_Button")
        self.saveSet_Button = QtWidgets.QPushButton(self.centralwidget)
        self.saveSet_Button.setGeometry(QtCore.QRect(450, 170, 81, 41))
        self.saveSet_Button.setObjectName("saveSet_Button")
        self.jpgCap_Button = QtWidgets.QPushButton(self.centralwidget)
        self.jpgCap_Button.setGeometry(QtCore.QRect(20, 140, 51, 41))
        self.jpgCap_Button.setAutoFillBackground(False)
        self.jpgCap_Button.setObjectName("jpgCap_Button")
        self.comboBox_loadSet = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_loadSet.setGeometry(QtCore.QRect(340, 250, 191, 22))
        self.comboBox_loadSet.setObjectName("comboBox_loadSet")
        self.loadSet_Button = QtWidgets.QPushButton(self.centralwidget)
        self.loadSet_Button.setGeometry(QtCore.QRect(430, 280, 101, 41))
        self.loadSet_Button.setObjectName("loadSet_Button")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(320, 140, 221, 20))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.reset_Button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_Button.setGeometry(QtCore.QRect(470, 340, 71, 31))
        self.reset_Button.setObjectName("reset_Button")
        self.lineEdit_saveName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_saveName.setGeometry(QtCore.QRect(330, 170, 111, 21))
        self.lineEdit_saveName.setText("")
        self.lineEdit_saveName.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_saveName.setObjectName("lineEdit_saveName")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(330, 220, 201, 20))
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(1)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.l_save_alert = QtWidgets.QLabel(self.centralwidget)
        self.l_save_alert.setGeometry(QtCore.QRect(330, 200, 111, 21))
        self.l_save_alert.setAlignment(QtCore.Qt.AlignCenter)
        self.l_save_alert.setObjectName("l_save_alert")
        self.lstDel_Button = QtWidgets.QPushButton(self.centralwidget)
        self.lstDel_Button.setGeometry(QtCore.QRect(340, 280, 81, 41))
        self.lstDel_Button.setObjectName("lstDel_Button")
        self.checkBox_openSet = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_openSet.setGeometry(QtCore.QRect(320, 70, 221, 41))
        self.checkBox_openSet.setChecked(False)
        self.checkBox_openSet.setObjectName("checkBox_openSet")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 560, 21))
        self.menubar.setObjectName("menubar")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit_1 = QtWidgets.QAction(MainWindow)
        self.actionExit_1.setCheckable(False)
        self.actionExit_1.setEnabled(True)
        self.actionExit_1.setObjectName("actionExit_1")
        self.menuTools.addAction(self.actionExit_1)
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        self.actionExit_1.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "lecture Capture [Ver.1.7]"))
        self.textBrowser_output.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pdfCap_Button.setText(_translate("MainWindow", "캡쳐\n"
"(PDF)"))
        self.l_dir.setText(_translate("MainWindow", "사진 저장 경로"))
        self.lineEdit_lctr.setText(_translate("MainWindow", "0"))
        self.l_lctr.setText(_translate("MainWindow", "몇 교시 입니까?"))
        self.cancle_Button.setText(_translate("MainWindow", "종료"))
        self.clear_Button.setText(_translate("MainWindow", "내역 지우기"))
        self.path_Button.setText(_translate("MainWindow", "수정"))
        self.l_sPoint.setText(_translate("MainWindow", "시작 위치 지정"))
        self.l_ePoint.setText(_translate("MainWindow", "끝 위치 지정"))
        self.position_Button.setText(_translate("MainWindow", "수정"))
        self.checkBox_lastChk.setText(_translate("MainWindow", "다음 시작 시, 마지막 설정 사용하기\n"
"(미구현)"))
        self.checkBox_endClr.setText(_translate("MainWindow", "캡쳐 종료시, 내역 자동 지우기"))
        self.setOpen_Button.setText(_translate("MainWindow", "설정▶"))
        self.label.setText(_translate("MainWindow", "< 설정 >"))
        self.folderOpen_Button.setText(_translate("MainWindow", "폴더 열기"))
        self.saveSet_Button.setText(_translate("MainWindow", "현재 설정\n"
"저장하기"))
        self.jpgCap_Button.setText(_translate("MainWindow", "캡쳐\n"
"(JPG)"))
        self.loadSet_Button.setText(_translate("MainWindow", "설정 불러오기"))
        self.reset_Button.setText(_translate("MainWindow", "초기화"))
        self.l_save_alert.setText(_translate("MainWindow", "(영어, 숫자만 입력)"))
        self.lstDel_Button.setText(_translate("MainWindow", "선택한 설정\n"
" 삭제하기"))
        self.checkBox_openSet.setText(_translate("MainWindow", "실행 시, 항상 설정탭 오픈\n"
"(미구현)"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.actionExit_1.setText(_translate("MainWindow", "Exit"))
        self.actionExit_1.setStatusTip(_translate("MainWindow", "프로그램을 종료합니다."))
        self.actionExit_1.setShortcut(_translate("MainWindow", "Ctrl+Q"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
